# -*- coding: utf-8 -*-
"""t02q03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tOKiza_Xsvif1UQh_VXW6qIeiEaLesq_
"""

from math import *

g = 32.17
s0 = 300
m = 0.25
k = 0.1
e = 2.7182818

epsilon = 0.000001

def s(t):
  return s0 - (m * g)/k * t + (m**2 * g)/k**2 * (1 - e**(-k * t/m))

def secant(a, b):
  if s(a) > -epsilon and s(a) < epsilon:
    print (a)
    return
  b = a - (s(a) * (a - b))/(s(a) - s(b))
  return secant(b, a)


if __name__ == '__main__':
  secant(-15,15)